version: '3.8'

services:
  nvim-dev:
    build:
      context: .
      dockerfile: dockerfile
    image: custom-nvim:latest
    container_name: custom-nvim-dev
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - TERM=xterm-256color
    volumes:
      - .:/workspace:rw
    command: ["/usr/bin/bash"]
    networks:
      - nvim-network

networks:
  nvim-network:
    driver: bridge
